name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libtinfo5 \
          libffi-dev \
          libssl-dev \
          python3-venv
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer Cython setuptools
        
    - name: Configure Buildozer
      run: |
        buildozer init
        # Упрощаем требования для первой сборки
        sed -i 's/requirements = .*/requirements = python3,kivy/' buildozer.spec
        sed -i 's/android.arch = .*/android.arch = arm64-v8a/' buildozer.spec
        
    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug
        ls -la bin/
        
    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: myapp-apk
        path: bin/*.apk
        retention-days: 30
